# Generated by Django 4.1.3 on 2023-02-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
